version: '3'

services:

  alfresco-core:
    image: hub.xenit.eu/alfresco-ethias:latest
    volumes:
    - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    ports:
    - 3333:8080
#    - :8000:8000
    environment:
    - DB_NAME=alfresco
    - DB_USERNAME=alfresco
    - DB_PASSWORD=admin
    - DB_URL=jdbc:postgresql://postgresql96:5432,postgresql10:5432/alfresco
    - DB_DRIVER=org.postgresql.Driver
    - SOLR_HOST=solr
    - SOLR_PORT=8082
    - SOLR_PORT_SSL=8444
    - ALFRESCO_HOST=localhost
    - ALFRESCO_PORT=8080
    - ALFRESCO_PORT_SSL=8443
    - ALFRESCO_PROTOCOL=http
    - SHARE_PROTOCOL=http
    - SHARE_PORT=8080
    - JAVA_XMS=512M
    - JAVA_XMX=2048M
    - SOLR_SSL=none
    - JMX_ENABLED=true
    - RMI_HOST=0.0.0.0
    - GLOBAL_content.transformer.RemoteJODConverter.endpoint=http://jodconverter:8080/converter/service
    - GLOBAL_ooo.enabled=false
    - GLOBAL_jodconverter.enabled=false

  postgresql96:
    image: hub.xenit.eu/postgres:9.6.6
    volumes:
    - postgres96:/var/lib/postgresql/data
    - share:/share
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
#    - PGCONF_log_duration=on
    - "PGCONF_shared_preload_libraries=pglogical"
    - "PGCONF_wal_level=logical"
    - "PGCONF_max_wal_senders=20"
    - "PGCONF_max_replication_slots=20"
    - PGHBAREPLACE=true
    - PGHBA_1=local all all trust
    - PGHBA_2=host all all 127.0.0.1/32 trust
    - PGHBA_3=host alfresco alfresco all md5
    - PGHBA_4=host replication postgres 172.18.0.0 255.255.255.0 trust
    - PGHBA_5=host alfresco postgres 172.18.0.0 255.255.255.0 trust
    restart: unless-stopped

  postgresql10:
    image: hub.xenit.eu/postgres:10.1
    volumes:
    - postgres10:/var/lib/postgresql/data
    - share:/share
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
#    - PGCONF_log_duration=on
    - "PGCONF_shared_preload_libraries=pglogical"
    - "PGCONF_wal_level=logical"
    - "PGCONF_max_wal_senders=20"
    - "PGCONF_max_replication_slots=20"
    - PGHBAREPLACE=true
    - PGHBA_1=local all all trust
    - PGHBA_2=host all all 127.0.0.1/32 trust
    - PGHBA_3=host alfresco alfresco all md5
    - PGHBA_4=host replication postgres 172.18.0.0 255.255.255.0 trust
    - PGHBA_5=host alfresco postgres 172.18.0.0 255.255.255.0 trust
    restart: unless-stopped

  jodconverter:
    image: hub.xenit.eu/jodconverter-ws
    restart: unless-stopped


volumes:
  alfresco:
  postgres96:
  postgres10:
  share: