version: '3'

services:
  postgresql96:
    image: hub.xenit.eu/postgres:local-9.6.6
    volumes:
    - postgres96:/var/lib/postgresql/data
    - share:/share
    ports:
    - ${DOCKER_IP}::5432
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=test
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
#    - PGCONF_log_duration=on
    - "PGCONF_shared_preload_libraries='pglogical'"
    - "PGCONF_wal_level='logical'"
    - "PGCONF_max_wal_senders=20"
    - "PGCONF_max_replication_slots=20"
    restart: unless-stopped

  postgresql10:
    image: hub.xenit.eu/postgres:local-10.1
    volumes:
    - postgres10:/var/lib/postgresql/data
    - share:/share
    ports:
    - ${DOCKER_IP}::5432
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=test
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
#    - PGCONF_log_duration=on
    - "PGCONF_shared_preload_libraries='pglogical'"
    - "PGCONF_wal_level='logical'"
    - "PGCONF_max_wal_senders=20"
    - "PGCONF_max_replication_slots=20"
    restart: unless-stopped

volumes:
  postgres96:
  postgres10:
  share:
